{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Проверка, что система вернула ошибку", "status": "passed", "start": 1727356459927, "stop": 1727356459927}], "attachments": [{"name": "stdout", "source": "bcd46d08-c877-47f7-b6da-e875483a5fd6-attachment.txt", "type": "text/plain"}], "start": 1727356458814, "stop": 1727356459929, "uuid": "9380e853-6171-47b1-a255-5b1f76543602", "historyId": "4b8f7121f2677ec2ae18b5989c1e8f88", "testCaseId": "4b8f7121f2677ec2ae18b5989c1e8f88", "fullName": "test.test_courier_login#test_login_with_invalid_credentials", "labels": [{"name": "feature", "value": "Авторизиция с невалидними данными"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_courier_login"}, {"name": "host", "value": "Liana_M"}, {"name": "thread", "value": "11256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_courier_login"}]}