{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Проверка, что система вернула ошибку", "status": "passed", "start": 1727349646409, "stop": 1727349646409}], "attachments": [{"name": "stdout", "source": "c96c4e3f-21b2-449f-9fd4-b204c38778a7-attachment.txt", "type": "text/plain"}], "start": 1727349644954, "stop": 1727349646412, "uuid": "c79697a3-b7a2-4192-ba2b-277fcc776164", "historyId": "4b8f7121f2677ec2ae18b5989c1e8f88", "testCaseId": "4b8f7121f2677ec2ae18b5989c1e8f88", "fullName": "test.test_courier_login#test_login_with_invalid_credentials", "labels": [{"name": "feature", "value": "Авторизиция с невалидними данными"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_courier_login"}, {"name": "host", "value": "Liana_M"}, {"name": "thread", "value": "18600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_courier_login"}]}